name: Update pkg.go.dev cache

on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `v0.8.4`

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: on

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: List
        run: ls -al
      - name: Create go.mod
        run: go mod init dummy
      - name: Update pkg.go.dev cache
        run: go get github.com/${{ github.repository }}@${{ github.ref_name }}
